export const HELPLINE_LOAD_REQUEST = "HELPLINE_LOAD_REQUEST";
export const HELPLINE_LOAD_SUCCESS = "HELPLINE_LOAD_SUCCESS";
export const HELPLINE_LOAD_FAIL = "HELPLINE_LOAD_FAIL";
export const HELPLINE_LOAD_RESET = "HELPLINE_LOAD_RESET";

export const HELPLINE_LOAD_SINGLE_REQUEST = "HELPLINE_LOAD_SINGLE_REQUEST";
export const HELPLINE_LOAD_SINGLE_SUCCESS = "HELPLINE_LOAD_SINGLE_SUCCESS";
export const HELPLINE_LOAD_SINGLE_FAIL = "HELPLINE_LOAD_SINGLE_FAIL";
export const HELPLINE_LOAD_SINGLE_RESET = "HELPLINE_LOAD_SINGLE_RESET";

export const HELPLINE_CREATE_REQUEST = 'HELPLINE_CREATE_REQUEST';
export const HELPLINE_CREATE_SUCCESS = 'HELPLINE_CREATE_SUCCESS';
export const HELPLINE_CREATE_FAIL = 'HELPLINE_CREATE_FAIL';
export const HELPLINE_CREATE_RESET = 'HELPLINE_CREATE_RESET';