export const ISSUE_TYPE_LOAD_REQUEST = "ISSUE_TYPE_LOAD_REQUEST";
export const ISSUE_TYPE_LOAD_SUCCESS = "ISSUE_TYPE_LOAD_SUCCESS";
export const ISSUE_TYPE_LOAD_FAIL = "ISSUE_TYPE_LOAD_FAIL";
export const ISSUE_TYPE_LOAD_RESET = "ISSUE_TYPE_LOAD_RESET";